# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_actuator_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSequence(object):
    def setupUi(self, DialogSequence):
        DialogSequence.setObjectName("DialogSequence")
        DialogSequence.resize(1462, 907)
        self.gridLayout = QtWidgets.QGridLayout(DialogSequence)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_save = QtWidgets.QPushButton(DialogSequence)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 4, 0, 1, 1)
        self.plt_sequence = GraphicsLayoutWidget(DialogSequence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.plt_sequence.sizePolicy().hasHeightForWidth())
        self.plt_sequence.setSizePolicy(sizePolicy)
        self.plt_sequence.setMinimumSize(QtCore.QSize(450, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plt_sequence.setFont(font)
        self.plt_sequence.setObjectName("plt_sequence")
        self.gridLayout.addWidget(self.plt_sequence, 1, 1, 5, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 2, 1)
        self.btn_start_stop = QtWidgets.QPushButton(DialogSequence)
        self.btn_start_stop.setObjectName("btn_start_stop")
        self.gridLayout.addWidget(self.btn_start_stop, 0, 0, 1, 1)
        self.comboBox_select_sequence = QtWidgets.QComboBox(DialogSequence)
        self.comboBox_select_sequence.setObjectName("comboBox_select_sequence")
        self.gridLayout.addWidget(self.comboBox_select_sequence, 0, 1, 1, 1)
        self.plainTextEdit_Script = QtWidgets.QPlainTextEdit(DialogSequence)
        self.plainTextEdit_Script.setObjectName("plainTextEdit_Script")
        self.gridLayout.addWidget(self.plainTextEdit_Script, 6, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogSequence)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 0, 1, 2)
        self.btn_reset_offsets = QtWidgets.QPushButton(DialogSequence)
        self.btn_reset_offsets.setObjectName("btn_reset_offsets")
        self.gridLayout.addWidget(self.btn_reset_offsets, 3, 0, 1, 1)
        self.btn_zero_laser = QtWidgets.QPushButton(DialogSequence)
        self.btn_zero_laser.setObjectName("btn_zero_laser")
        self.gridLayout.addWidget(self.btn_zero_laser, 1, 0, 1, 1)
        self.btn_zero_force = QtWidgets.QPushButton(DialogSequence)
        self.btn_zero_force.setObjectName("btn_zero_force")
        self.gridLayout.addWidget(self.btn_zero_force, 2, 0, 1, 1)

        self.retranslateUi(DialogSequence)
        self.buttonBox.accepted.connect(DialogSequence.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogSequence.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogSequence)

    def retranslateUi(self, DialogSequence):
        _translate = QtCore.QCoreApplication.translate
        DialogSequence.setWindowTitle(_translate("DialogSequence", "Dialog"))
        self.btn_save.setText(_translate("DialogSequence", "Save"))
        self.btn_start_stop.setText(_translate("DialogSequence", "Start"))
        self.btn_reset_offsets.setText(_translate("DialogSequence", "Reset Offsets"))
        self.btn_zero_laser.setText(_translate("DialogSequence", "Zero Laser"))
        self.btn_zero_force.setText(_translate("DialogSequence", "Zero Force"))
from pyqtgraph import GraphicsLayoutWidget
