# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_config_name.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_config_name(object):
    def setupUi(self, Dialog_config_name):
        Dialog_config_name.setObjectName("Dialog_config_name")
        Dialog_config_name.resize(400, 86)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_config_name)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_config_name)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_config_name = QtWidgets.QLineEdit(Dialog_config_name)
        self.lineEdit_config_name.setObjectName("lineEdit_config_name")
        self.verticalLayout.addWidget(self.lineEdit_config_name)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_config_name)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_config_name)
        self.buttonBox.accepted.connect(Dialog_config_name.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_config_name.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_config_name)

    def retranslateUi(self, Dialog_config_name):
        _translate = QtCore.QCoreApplication.translate
        Dialog_config_name.setWindowTitle(_translate("Dialog_config_name", "Dialog"))
        self.label.setText(_translate("Dialog_config_name", "Name the configuration"))
