# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_stiffness.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogStiffness(object):
    def setupUi(self, DialogStiffness):
        DialogStiffness.setObjectName("DialogStiffness")
        DialogStiffness.resize(756, 795)
        self.gridLayout = QtWidgets.QGridLayout(DialogStiffness)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_formula = QtWidgets.QLabel(DialogStiffness)
        self.lbl_formula.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_formula.setObjectName("lbl_formula")
        self.gridLayout.addWidget(self.lbl_formula, 8, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_source_x = QtWidgets.QComboBox(DialogStiffness)
        self.comboBox_source_x.setObjectName("comboBox_source_x")
        self.comboBox_source_x.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_source_x)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_source_y = QtWidgets.QComboBox(DialogStiffness)
        self.comboBox_source_y.setObjectName("comboBox_source_y")
        self.comboBox_source_y.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_source_y)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_start_stop = QtWidgets.QPushButton(DialogStiffness)
        self.btn_start_stop.setObjectName("btn_start_stop")
        self.verticalLayout.addWidget(self.btn_start_stop)
        self.btn_zero_force = QtWidgets.QPushButton(DialogStiffness)
        self.btn_zero_force.setEnabled(True)
        self.btn_zero_force.setObjectName("btn_zero_force")
        self.verticalLayout.addWidget(self.btn_zero_force)
        self.btn_zero_laser = QtWidgets.QPushButton(DialogStiffness)
        self.btn_zero_laser.setEnabled(True)
        self.btn_zero_laser.setObjectName("btn_zero_laser")
        self.verticalLayout.addWidget(self.btn_zero_laser)
        self.btn_approx = QtWidgets.QPushButton(DialogStiffness)
        self.btn_approx.setObjectName("btn_approx")
        self.verticalLayout.addWidget(self.btn_approx)
        self.btn_save = QtWidgets.QPushButton(DialogStiffness)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout.addWidget(self.btn_save)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogStiffness)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 1, 1, 1)
        self.plt_stiffness = GraphicsLayoutWidget(DialogStiffness)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.plt_stiffness.sizePolicy().hasHeightForWidth())
        self.plt_stiffness.setSizePolicy(sizePolicy)
        self.plt_stiffness.setMinimumSize(QtCore.QSize(450, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plt_stiffness.setFont(font)
        self.plt_stiffness.setObjectName("plt_stiffness")
        self.gridLayout.addWidget(self.plt_stiffness, 1, 1, 1, 1)

        self.retranslateUi(DialogStiffness)
        self.buttonBox.accepted.connect(DialogStiffness.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogStiffness.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogStiffness)

    def retranslateUi(self, DialogStiffness):
        _translate = QtCore.QCoreApplication.translate
        DialogStiffness.setWindowTitle(_translate("DialogStiffness", "Dialog"))
        self.lbl_formula.setText(_translate("DialogStiffness", "y=mx+b"))
        self.comboBox_source_x.setItemText(0, _translate("DialogStiffness", "X Data"))
        self.comboBox_source_y.setItemText(0, _translate("DialogStiffness", "Y Data"))
        self.btn_start_stop.setText(_translate("DialogStiffness", "Start"))
        self.btn_zero_force.setText(_translate("DialogStiffness", "Zero Force"))
        self.btn_zero_laser.setText(_translate("DialogStiffness", "Zero Laser"))
        self.btn_approx.setText(_translate("DialogStiffness", "Approx"))
        self.btn_save.setText(_translate("DialogStiffness", "Save"))
from pyqtgraph import GraphicsLayoutWidget
